scrape_configs:
  - job_name: 'java-service'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api:8080']
        labels:
          application: 'java-service'